<div class="row">
    <div class="span12">
        <h2>Error with your submission</h2>
        <p class="help-block error">
            There were one or more errors with your submission; please correct and re-submit!
        </p>
<?php
$form = $this->form;
$form->setAttributes(array(
    'method' => 'post',
    'action' => $this->url('phly-peep/submit'),
    'class'  => 'well form-vertical',
));
echo $this->form()->openTag($form);

$peepElement = $form->get('peep_text');
$peepElement->setAttribute('class', 'span4');
echo $this->formRow($peepElement);
echo $this->formInput($form->get('secure'));
?>
<br />
<button type="submit" class="btn">Peep!</button>
<?php echo $this->form()->closeTag() ?>
    </div>
</div>
